{{ if not .Values.general.storage.customVolume }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.general.storage.pvcName }}
spec:
  accessModes:
    - {{ .Values.general.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.general.storage.size }}
  storageClassName: {{ if (kindIs "invalid" .Values.general.storage.pvcStorageClass) }}""{{- else }}{{ .Values.general.storage.pvcStorageClass | quote }}{{- end }}
{{ end }}
